blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.index,name='index'),
    path('about/',views.about,name='about'),
    path('category/<slug:category_name_slug>/',views.show_category,name='show_category'),
    path('add_category/',views.add_category,name='add_category'),
    path('<category>/add_page/',views.add_page,name='add_page'),
    path('search/',views.search,name='search'),
    path('goto/<id>',views.go_to,name='go_to'),
    path('register/user_profile/',views.user_profile,name='register_profile'),
    path('user/profile/',views.profile,name='profile'),
]

weblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from registration.forms import RegistrationForm
from django import forms

class MyRegisterationView(RegistrationView):
    def get_success_url(self, user):
        return '/blog/register/user_profile/'



urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
    path('blog/accounts/register/',MyRegisterationView.as_view(),name="registration_register"),
    path('blog/accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=128,unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args,**kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category,on_delete=True)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=True)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='user_picture',blank=True)

    def __str__(self):
        return self.user.username

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Category,Page, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,help_text='Please enter the category name.')
    views = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(),required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,help_text='Please enter the title of the page.')
    url = forms.URLField(max_length=200,help_text='Please enter the URL of the page.')
    views = forms.IntegerField(widget=forms.HiddenInput(),initial=0)

    class Meta:
        model = Page
        exclude = ('catagory',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('website','picture')

blog/views.py
from datetime import datetime

from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import generic

from blog.webhose_search import run_query
from .forms import CategoryForm, PageForm, UserProfileForm
from .models import Category, Page, UserProfile


class IndexViews(generic.ListView):
    template_name = 'blog/index.html'


def get_server_side_cookie(request,cookie,defuale_value=None):
    val = request.session.get(cookie)
    if not val:
        val = defuale_value
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request,'visits','1'))

    last_visit_cookie = get_server_side_cookie(request,'last_visit',str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = str(datetime.now())
    request.session['visits'] = visits


def index(request):
    request.session.set_test_cookie()

    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:3]
    context_dict = {
        'categories': category_list,
        'pages': page_list,
    }

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    response =  render(request, 'blog/index.html', context=context_dict)
    return response


def about(request):
    if request.session.test_cookie_worked():
        print('TEST COOKIE WORKED!')
        request.session.delete_test_cookie()
    context_dict = {'message': 'This tutorial has been put together by simon.'}
    return render(request, 'blog/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None

    return render(request, 'blog/category.html', context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    context_dict = {'form':form,}
    return render(request, 'blog/add_category.html',context=context_dict)

@login_required
def add_page(request, category):
    category = get_object_or_404(Category, slug=category)
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save(commit=True)
            page.category = category
            page.save()
            return show_category(request, category.slug)
    else:
        print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'blog/add_page.html', context_dict)

def search(request):
    result_list=[]
    query = ''
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
    return render(request,'blog/search.html',{'result_list':result_list,'query':query})

def go_to(request,id):
    page = Page.objects.get(id=id)
    if page:
        page.views += 1
        page.save()
    return HttpResponseRedirect(page.url)

@login_required
def user_profile(request):
    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return index(request)
    return render(request,'blog/register_user_profile.html',{'form':form})

@login_required
def profile(request):
    user = request.user
    profile = UserProfile.objects.get(user=user)
    profile_dict = {
        'username':user,
        'email':user.email,
        'url':profile.website,
        'picture':profile.picture
    }
    return render(request, 'blog/profile.html', profile_dict)

templates/blog/about.html
{% extends 'blog/base.html' %}

{% block title_block %}
About
{% endblock %}
{% block body_block %}
    <h1>About</h1>
    <div>
        Hello!<br />
        <strong>{{ message }}</strong><br />
    </div>
{#    <div>#}
{#        <a href="/blog/">Index</a><br />#}
{#        <img src="{{ MEDIA_URL }}cat.jpeg" alt="Picture of Range">#}
{#    </div>#}
{% endblock %}

templates/blog/add_category.html
{% extends 'blog/base.html' %}
{% load bootstrap_toolkit %}

{% block title_block %}
Add_a_Category
{% endblock %}

{% block body_block %}
        <form id="category_form" method="post" action="{% url 'blog:add_category' %}">
        <h2 class="form-signin-heading"> Add a Category</h2>
            {% csrf_token %}
            {% bootstrap_form form layout="vertical" %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit"> Add Category</button>
        </form>
{% endblock %}

templates/blog/add_page.html
{% extends 'blog/base.html' %}

{% block title_block %}
Add_a_Page
{% endblock %}

{% block body_block %}
    {% if category %}
        <form role="form" id="page_form" method="post" action="{% url 'blog:add_page' category=category.slug %}">
        <h2 class="form-signin-heading"> Add a Page to<a href="{% url 'blog:show_category' category.slug %}">{{ category.name }}</a></h2>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit"> Add Page</button>
        </form>
    {% else %}
    <p>This is category does not exist.</p>
    {% endif %}
{% endblock %}

templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>Blog- {% block title_block %}{% endblock %}</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    <script type="text/javascript">
      $(function() {
        $('input#category-search').on('keyup', function(e) {
          var searchQuery = $(this).val().toUpperCase();
          $('li.category_link').each(function() {
            var elem = $(this),
                tableName = elem.find('a').prop('innerText').toUpperCase();
            elem.toggle(tableName.indexOf(searchQuery) != -1);
          });
        });
      });
     </script>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'blog:index' %}">Blog</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:index' %}">Index <span class="sr-only">(current)</span></a>
          </li>
            {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:add_category' %}">Add New Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_logout' %}?next=/blog/">Logout</a>
          </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register' %}">Register</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:about' %}">About</a>
            </li>
        </ul>
      </div>
    </nav>

    <div class="container-fluid" style="padding-top: 50px;">
      <div class="row">
        <div class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar pt-5">
            {% block sidebar_block %}
                <input class="form-control input-sm" id="category-search" placeholder="filter category" type="text" />
                {% get_category_list category %}
                <div class="col-sm-8">
                <h5>Search with BLog</h5>
                <form class="form-inline" id="user_form" method="post" action="{% url 'blog:search' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-cotrol" type="text" size="50" name="query" value="{{ query }}" id="query" style="width: 40%;"/>
                    </div>
                    <button class="btn btn-primary btn-sm" type="submit" name="submit" value="Search">Search</button>
                </form>
                </div>
            {% endblock %}
        </div>

        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
            {% block body_block %}
            {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/blog/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>Blog- {% block title_block %}{% endblock %}</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Dashboard</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:index' %}">Index <span class="sr-only">(current)</span></a>
          </li>
            {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'blog:add_category' %}">Add New Category</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'auth_logout' %}?next=/blog/">Logout</a>
          </li>
            {% else %}
            <li class="nav-item">
                <a href="{% url 'auth_login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'registration_register' %}">Register</a>
            </li>

        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
            {% block sidebar_block %}
            {% endblock %}
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
            {% block body_block %}
            {% endblock %}
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/blog/category.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{% url 'blog:go_to' page.id %}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No page currently in category.</strong>
        {% endif %}
    {% else %}
        The specified category does not exist!
    {% endif %}
    <br />
    {% if category %}
        {% if user.is_authenticated %}
        <strong>Add Page</strong><br />
        <a href="{% url 'blog:add_page' category=category.slug %}">Add a Page</a><br />
        {% endif %}
    {% endif %}
{% endblock %}

templates/blog/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
            <li class="category_link"><strong><a href="{% url 'blog:show_category' c.slug %}">{{ c.name }}</a></strong></li>
            {% else %}
            <li class="category_link"><a href="{% url 'blog:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/blog/index.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block title_block %}
Index
{% endblock %}

{% block body_block %}
    <div class="jumbotron">
    <h1>WeBlog</h1>
    <p>
        {% if user.is_authenticated %}
        Hello {{ user.username }}
        {% else %}
        Hello!
        {% endif %}
    </p>
    </div>
    <div class="row marketing">
        <div class="col-lg-6">
            <strong>Most Liked Categories:</strong>
            {% if categories %}
            <ul class="list-group">
                {% for category in categories %}
                    <li class="list-group-item"><a href="{% url 'blog:show_category' category.slug %}">{{ category.name }} </a> <span class="badge badge-pill badge-primary">{{category.likes}}</span></li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
        </div>

        <div class="col-lg-6">
            <strong>Most Viewed Pages:</strong>
            {% if pages %}
            <ul class="list-group">
                {% for page in pages %}
                    <li class="list-group-item">
                        <a href="{% url 'blog:go_to' page.id %}">{{ page.title }} </a> <span class="badge badge-pill badge-primary">{{page.views}}</span>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
                There is no page.
            {% endif %}
        </div>
    </div>

    <div>
        <img src="{% static "images/rango.jpeg" %}" alt="Picture of Range" />
    </div>
{% endblock %}

templates/blog/profile.html
{% extends 'blog/base.html' %}

{% block title_block %}
Profile
{% endblock %}
{% block body_block %}
    <h3>{{ username }}</h3>
    <h4>{{ email }}</h4>
    <a href="{{ url }}">{{ url }}</a><br />
    <img src="{{ MEDIA_URL }}{{ picture }}" />
{% endblock %}

templates/blog/register_user_profile.html
{% extends 'blog/base.html' %}
{% load bootstrap_toolkit %}

{% block title_block %}
Edit_Profile
{% endblock %}

{% block body_block %}
        <form id="category_form" method="post" action="." enctype="multipart/form-data">
        <h2 class="form-signin-heading"> Edit Profile</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <br />
            <button class="btn btn-primary" type="submit" name="submit"> Submit</button>
        </form>
{% endblock %}

templates/blog/search.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block title_block %}
Search
{% endblock %}

{% block body_block %}

<div>
    {% if result_list %}
    <h3>Results</h3>
    <div class="list-group">
        {% for result in result_list %}
        <div class="list-group-item">
            <h4 class="list-group-item-heading">
                <a href="{{ result.link }}">{{ result.title }}</a>
            </h4>
            <p class="list-group-item-text">{{ result.summary }}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>

{% endblock %}